django-views-practice/app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('add/', views.add, name='add'),
]

django-views-practice/view_practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

django-views-practice/app/models.py
from django.db import models

# Create your models here.

django-views-practice/app/views.py
from django.shortcuts import render


def add(request):
    num1 = request.GET.get('num1')
    num2 = request.GET.get('num2')

    if num1 is not None and num2 is not None:
        num1 = float(num1)
        num2 = float(num2)
        answer = num1 + num2
        return render(request, 'app/add.html', {'answer': answer})
    else:
        return render(request, 'app/add.html')

django-views-practice/app/templates/app/add.html
{% block body %}

<form action="{% url 'app:add' %}" method="GET" role="form">
    <div class="form-group">
        <label for="num1">Num 1</label>
        <input type="number" name="num1" class="form-control" placeholder="Num 1">
    </div>
    <div class="form-group">
        <label for="num2">Num 2</label>
        <input type="number" name="num2" class="form-control" placeholder="Num 1">
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
    {% if answer != None %}
        <h3>Answer: {{ answer }}</h3>
    {% endif %}
</form>

{% endblock body %}

django-views-practice/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django View Practice</title>
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
</head>
<body>
    {% block body %}
    {% endblock body %}
    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>